name: ci-test
on: { push: { branches: [ "**" ] } }
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "18.x" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/core@0.5 -eI bash/verify-alias.js
